from pydantic import BaseModel
from typing import Dict
from datetime import datetime, timezone

class LiquidityRequest(BaseModel):
    """
    Represents a structured liquidity request from a business agent to a bank agent.

    Use case:
    - Generated by the Business Liquidity Agent when a cash-flow shortfall is projected.
    - Contains requested amount, duration, and supporting risk metrics.
    - Submitted to a Bank Credit Agent for evaluation.

    Purpose:
    - Standardises liquidity requests for automated, auditable, and policy-compliant processing.
    """
    business_id: str
    principal_address: str
    requested_amount: float
    unlock_timestamp: datetime
    metrics: Dict[str, float]